version: 1

strategies:
  - dataresource: load_data
    # use moltemplate_input2 for a shorter run with lammps
    downloadUrl: "file:///tmp/OntoTrans2ndWorkshop/data/multidata_moltemplateinput.xlsx"
    mediaType: application/vnd.dlite-xlsx
    configuration:
      metadata: http://openmodel.eu/meta/0.1/MoltemplateInputSimulationParameters
      excel_config:
        worksheet: "SimulationParameters"
        header_row: "1"
        row_from: "2"
        row_to: "2"
      label: moltemplate_input_2

  - mapping: mappings
    mappingType: mappings
    prefixes:
      emmo: http://emmo.info/emmo#
      map: http://emmo.info/domain-mappings#
      param: http://openmodel.eu/meta/0.1/MoltemplateInputSimulationParameters#
      demonto: http://openmodel.eu/0.1/domainonto#
    triples:
      - ["param:number_of_steps", "map:mapsTo", "demonto:Steps"]
      - ["param:equilibration_steps", "map:mapsTo", "demonto:StepsToEquilibration"]
      - ["param:s_", "map:mapsTo", "demonto:Sss"]
      - ["param:timestep", "map:mapsTo", "demonto:TimeStep"]
      - ["param:production_steps", "map:mapsTo", "demonto:StepsInProduction"]
      - ["param:gridsize", "map:mapsTo", "demonto:GridSize"]
      - ["param:gridspacing", "map:mapsTo", "demonto:GridSpacing"]


pipelines:
  pipe: load_data | mappings
